default:
  image: rockylinux:9.3
  tags:
    - shared-pure

before_script:
  - export MAXMIND_TOKEN=${MAXMIND_TOKEN}

stages:
  - build_and_pull
  - send_to_cribl

build and pull the data:
  stage: build_and_pull
  script:
    - dnf update -y &> /dev/null
    - dnf install -y git python3 python3.9-pip &> /dev/null
    - pip3 install wheel &> /dev/null
    - git clone https://github.com/splunk/asparser
    - cd asparser
    - python3 -m pip install -r requirements.txt . &> /dev/null
    - asparser -o results.json &> /dev/null
  artifacts:
    paths:
      - asparser/results.json
    expire_in: 1 hour

send the data:
  stage: send_to_cribl
  script:
    - dnf update -y &> /dev/null
    - dnf install -y python3 python3.9-pip &> /dev/null
    - pip3 install requests &> /dev/null
    - python3 send_to_cribl.py